groups:
  - name: disk_usage_alerts
    rules:
      - alert: DiskUsageHigh
        expr: (node_filesystem_size_bytes  - node_filesystem_avail_bytes   ) / node_filesystem_size_bytes    > 0.7
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Disk usage is above 70%"
          description: "Disk usage is above 70% on {{ $labels.instance }}."

      - alert: DiskUsageMedium
        expr: (node_filesystem_size_bytes  - node_filesystem_avail_bytes   ) / node_filesystem_size_bytes    == 0.5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Disk usage is above 50%"
          description: "Disk usage is above 50% on {{ $labels.instance }}."

      - alert: DiskUsageLow
        expr: (node_filesystem_size_bytes  - node_filesystem_avail_bytes   ) / node_filesystem_size_bytes    == 0.3
        for: 1m
        labels:
          severity: info
        annotations:
          summary: "Disk usage is above 30%"
          description: "Disk usage is above 30% on {{ $labels.instance }}."

      - alert: DiskUsageInfo
        expr: (node_filesystem_size_bytes  - node_filesystem_avail_bytes   ) / node_filesystem_size_bytes    >= 0.01
        for: 1s
        labels:
          severity: info
        annotations:
          summary: "Disk usage is above 10%"
          description: "Disk usage is above 10% on {{ $labels.instance }}."
