global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.248.77:9100'] 
#./node_exporter --collector.textfile.directory=/home/prakharverma/Documents/Mini-Project/diskusagecronupdate/node_exporter/

  - job_name: 'flask_exporter'
    static_configs:
      - targets: ['192.168.248.77:5000']

rule_files:
  - "prometheus_rules.yml"
